(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.MKEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const SIZES_UM=[25400,19000,12700,9500,6700,4750,3350,2360,1700,1180,850,600,425,300,212,150,106,75,53,38],EPS=1e-12,RHO_WATER=1;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),sum=a=>a.reduce((x,y)=>x+y,0),zeros=()=>SIZES_UM.map(()=>0);
function normalized(a){const s=sum(a);return s>EPS?a.map(x=>Math.max(0,x)/s):zeros();}
function weibullFractions(p80,beta=1.15){p80=Math.max(1,p80);const k=p80/Math.pow(-Math.log(.2),1/Math.max(.2,beta)),passing=d=>1-Math.exp(-Math.pow(d/k,beta)),f=zeros();f[0]=1-passing(SIZES_UM[0]);for(let i=1;i<f.length;i++)f[i]=passing(SIZES_UM[i-1])-passing(SIZES_UM[i]);f[f.length-1]+=passing(SIZES_UM.at(-1));return normalized(f);}
function cumulativePassing(frac){const f=normalized(frac),out=zeros();let finer=0;for(let i=f.length-1;i>=0;i--){out[i]=finer;finer+=f[i];}return out;}
function p80FromFractions(frac){const p=cumulativePassing(frac);for(let i=0;i<p.length-1;i++)if(p[i]>=.8&&p[i+1]<=.8){const dy=p[i+1]-p[i];return Math.exp(Math.log(SIZES_UM[i])+(.8-p[i])*(Math.log(SIZES_UM[i+1])-Math.log(SIZES_UM[i]))/(Math.abs(dy)>EPS?dy:-EPS));}return p[0]<.8?SIZES_UM[0]:SIZES_UM.at(-1);}
function bondEnergy(wi,f80,p80){return wi>0&&f80>0&&p80>0?Math.max(0,10*wi*(1/Math.sqrt(p80)-1/Math.sqrt(f80))):NaN;}
function pulpProperties(solidsT,waterT,oreDensity=2.7){solidsT=Math.max(0,solidsT);waterT=Math.max(0,waterT);const total=solidsT+waterT,volume=solidsT/oreDensity+waterT;return{solidsPct:total>EPS?100*solidsT/total:0,density:volume>EPS?total/volume:1,volumeM3:volume};}
function defaultConfig(o){return Object.assign({freshSolidsTph:100,feedF80Um:10000,wiKwhT:14,oreDensityTpm3:2.7,feedMoisturePct:3,millWaterM3h:60,millVolumeM3:120,ballChargePct:32,millSpeedCriticalPct:75,installedPowerKw:2200,mechanicalEfficiencyPct:92,tauPSDMin:4,tauHoldMin:2,initialMillSolidsT:85,sumpVolumeM3:160,sumpInitialLevelPct:55,sumpWaterM3h:20,sumpLevelSetpointPct:55,pumpControlMode:'auto',pumpSpeedPct:70,pumpMaxFlowM3h:360,pumpLevelGain:2,pumpIntegralTimeMin:5,pumpMinimumControlPct:20,cycloneDiameterMm:500,activeCyclones:6,feedPressureKpa:100,apexDiameterMm:100,vortexFinderDiameterMm:180,cycloneBypassPct:12,cycloneImperfection:.32,tauCycloneMin:.15,d50cBaseUm:105,breakageCalibration:115,minimumPowerFraction:.18,stabilityWindowMin:2,tolerances:{p80Rate:.15,inventoryRate:.03,clRate:.25,ufRate:.08,levelRate:.03,densityRate:.001,solids:.001,water:.001}},o||{});}
function validateConfig(c){['freshSolidsTph','feedF80Um','wiKwhT','oreDensityTpm3','millVolumeM3','installedPowerKw','tauHoldMin','sumpVolumeM3','pumpMaxFlowM3h','pumpLevelGain','pumpIntegralTimeMin','cycloneDiameterMm','activeCyclones','feedPressureKpa','apexDiameterMm','vortexFinderDiameterMm','cycloneImperfection','d50cBaseUm'].forEach(k=>{if(!(c[k]>0)||!Number.isFinite(c[k]))throw Error('Entrada inválida: '+k);});['feedMoisturePct','ballChargePct','millSpeedCriticalPct','mechanicalEfficiencyPct','sumpInitialLevelPct','sumpLevelSetpointPct','pumpSpeedPct','pumpMinimumControlPct','cycloneBypassPct'].forEach(k=>{if(c[k]<0||c[k]>100)throw Error('Porcentaje fuera de rango: '+k);});if(!['auto','manual'].includes(c.pumpControlMode))throw Error('Modo de bomba inválido');}
function moistureWaterTph(c){return c.freshSolidsTph*c.feedMoisturePct/Math.max(EPS,100-c.feedMoisturePct);}
// PROVISIONAL/CALIBRABLE: correction around base d50; not a validated cyclone design correlation.
function effectiveD50(c,pulp,q){const qPer=q/Math.max(1,c.activeCyclones),pCorr=Math.pow(100/Math.max(20,c.feedPressureKpa),.25),qCorr=Math.pow(Math.max(.2,qPer/(220/6)),-.10),rhoCorr=Math.pow(Math.max(.7,pulp.density/1.35),.12),geom=Math.pow(c.cycloneDiameterMm/500,.5)*Math.pow(c.vortexFinderDiameterMm/180,.15)*Math.pow(100/c.apexDiameterMm,.08);return clamp(c.d50cBaseUm*pCorr*qCorr*rhoCorr*geom,c.d50cBaseUm*.45,c.d50cBaseUm*2.2);}
function partitionToUF(size,c,d50){const slope=clamp(1.5/c.cycloneImperfection,1.2,12),b=c.cycloneBypassPct/100;return clamp(b+(1-b)/(1+Math.pow(d50/Math.max(1,size),slope)),b,.999);}
function classify(solids,water,c,pulp,q){const d50=effectiveD50(c,pulp,q),uf=zeros(),of=zeros();for(let i=0;i<solids.length;i++){const e=partitionToUF(SIZES_UM[i],c,d50);uf[i]=solids[i]*e;of[i]=solids[i]-uf[i];}const fs=sum(solids),split=fs>EPS?sum(uf)/fs:0,geometry=(c.apexDiameterMm/100)/(c.vortexFinderDiameterMm/180),wr=clamp(.08+.58*split+.10*(geometry-1),c.cycloneBypassPct/100,.88),wuf=water*wr;return{uf,of,waterUF:wuf,waterOF:water-wuf,waterRecovery:wr,d50,F_cyclone:fs,F_UF:sum(uf),F_OF:sum(of),split_UF:split,p80UF:p80FromFractions(uf),p80OF:p80FromFractions(of)};}
function powerForInventory(M,c){const load=clamp(M/Math.max(1,c.initialMillSolidsT),c.minimumPowerFraction,1),speed=clamp(c.millSpeedCriticalPct/75,.5,1.15);return Math.min(c.installedPowerKw,c.installedPowerKw*load*speed)*c.mechanicalEfficiencyPct/100;}
function breakageRates(power,M,c){const intensity=c.breakageCalibration*power/Math.max(EPS,c.wiKwhT*M*60);return SIZES_UM.map(d=>intensity*clamp(Math.pow(d/c.feedF80Um,.32),.18,2.2));}
function flowModel(s,c){const millS=sum(s.millMass),tau=Math.max(.05,c.tauHoldMin),millOut=s.millMass.map(x=>x/tau),millWaterOut=s.millWater/tau,sump=pulpProperties(sum(s.sumpMass),s.sumpWater,c.oreDensityTpm3),level=100*sump.volumeM3/c.sumpVolumeM3,minSpeed=sump.volumeM3>EPS?c.pumpMinimumControlPct:0,error=level-c.sumpLevelSetpointPct,integral=s.pumpIntegral||0,rawSpeed=c.pumpControlMode==='auto'?c.pumpSpeedPct+c.pumpLevelGain*error+integral:c.pumpSpeedPct,speed=clamp(rawSpeed,minSpeed,100),ki=c.pumpLevelGain/Math.max(.1,c.pumpIntegralTimeMin),dPumpIntegral=c.pumpControlMode==='auto'&&!((rawSpeed>=100&&error>0)||(rawSpeed<=minSpeed&&error<0))?ki*error:0,qDemand=c.pumpMaxFlowM3h*speed/100,q=Math.min(qDemand,sump.volumeM3*60/.25),sumpS=sum(s.sumpMass),sc=sump.volumeM3>EPS?sumpS/sump.volumeM3:0,wc=sump.volumeM3>EPS?s.sumpWater/sump.volumeM3:1,pumpS=s.sumpMass.map(x=>q*sc*x/Math.max(EPS,sumpS)/60),pumpW=q*wc/60,pulp=pulpProperties(sum(pumpS)*60,pumpW*60,c.oreDensityTpm3),cyc=classify(pumpS,pumpW,c,pulp,q),freshFrac=weibullFractions(c.feedF80Um),fresh=c.freshSolidsTph/60,input=freshFrac.map((x,i)=>x*fresh+cyc.uf[i]),power=powerForInventory(millS,c),rates=breakageRates(power,millS,c),broken=zeros();for(let i=0;i<s.millMass.length;i++){const b=rates[i]*s.millMass[i];broken[i]-=b;if(i===broken.length-1)broken[i]+=b;else{broken[i+1]+=.72*b;broken[Math.min(i+2,broken.length-1)]+=.28*b;}}const dMillMass=input.map((x,i)=>x-millOut[i]+broken[i]),dMillWater=c.millWaterM3h/60+moistureWaterTph(c)/60+cyc.waterUF-millWaterOut,dSumpMass=millOut.map((x,i)=>x-pumpS[i]),dSumpWater=millWaterOut+c.sumpWaterM3h/60-pumpW;return{dMillMass,dMillWater,dSumpMass,dSumpWater,dPumpIntegral,millOut,millWaterOut,pumpS,pumpW,qPump:q,effectiveSpeed:speed,cyc,power,feedPulp:pulp,sumpProps:sump,level};}
function metrics(s,c,d=flowModel(s,c)){const Ffresh=c.freshSolidsTph,Fmill=sum(d.millOut)*60,Fcycl=sum(d.pumpS)*60,Fuf=d.cyc.F_UF*60,Fof=d.cyc.F_OF*60,Wmoist=moistureWaterTph(c),WmillIn=c.millWaterM3h+Wmoist+d.cyc.waterUF*60,WmillOut=d.millWaterOut*60,WsumpIn=WmillOut+c.sumpWaterM3h,Wpump=d.pumpW*60,Wuf=d.cyc.waterUF*60,Wof=d.cyc.waterOF*60,millP=pulpProperties(Fmill,WmillOut,c.oreDensityTpm3),sumpP=d.sumpProps,cycP=d.feedPulp,ufP=pulpProperties(Fuf,Wuf,c.oreDensityTpm3),ofP=pulpProperties(Fof,Wof,c.oreDensityTpm3),millInP=pulpProperties(Ffresh+Fuf,c.millWaterM3h+Wmoist+Wuf,c.oreDensityTpm3),dS=(sum(d.dMillMass)+sum(d.dSumpMass))*60,dW=(d.dMillWater+d.dSumpWater)*60;return{t:s.t,M_mill:sum(s.millMass),millWaterMassT:s.millWater,sumpSolidsMassT:sum(s.sumpMass),sumpWaterMassT:s.sumpWater,sumpVolumeM3:sumpP.volumeM3,sumpLevelPct:d.level,sumpAlarm:d.level>=100?'REBALSE':d.level>90?'NIVEL ALTO':d.level<10?'NIVEL BAJO':'NORMAL',Power_mill:d.power,specificEnergy:d.power/Math.max(EPS,Ffresh),F_fresh:Ffresh,F_mill:Fmill,F_cyclone:Fcycl,F_UF:Fuf,F_OF:Fof,CL:100*Fuf/Math.max(EPS,Ffresh),split_UF:d.cyc.split_UF,P80_feed:c.feedF80Um,P80_mill:p80FromFractions(d.millOut),P80_cyclone:p80FromFractions(d.pumpS),P80_UF:d.cyc.p80UF,P80_OF:d.cyc.p80OF,W_mill_in:WmillIn,W_mill_out:WmillOut,W_sump_fresh:c.sumpWaterM3h,W_cyclone:Wpump,W_UF:Wuf,W_OF:Wof,R_mass:Ffresh+Fuf-Fmill,R_cyclone:Fcycl-Fuf-Fof,R_water_mill:WmillIn-WmillOut-d.dMillWater*60,R_water_sump:WsumpIn-Wpump-d.dSumpWater*60,R_water_cyclone:Wpump-Wuf-Wof,solidsInventoryRate:dS,waterInventoryRate:dW,systemSolidsResidual:Ffresh-Fof-dS,systemWaterResidual:c.millWaterM3h+Wmoist+c.sumpWaterM3h-Wof-dW,solidsPctMillIn:millInP.solidsPct,solidsPctMillOut:millP.solidsPct,solidsPctSump:sumpP.solidsPct,solidsPctCyclone:cycP.solidsPct,solidsPctUF:ufP.solidsPct,solidsPctOF:ofP.solidsPct,densityMill:millP.density,densitySump:sumpP.density,densityCyclone:cycP.density,densityUF:ufP.density,densityOF:ofP.density,Q_mill:millP.volumeM3,Q_sump_in:millP.volumeM3+c.sumpWaterM3h,Q_pump:d.qPump,Q_cyclone:d.qPump,Q_UF:ufP.volumeM3,Q_OF:ofP.volumeM3,pumpSpeedEffectivePct:d.effectiveSpeed,qPerCyclone:d.qPump/c.activeCyclones,d50c:d.cyc.d50,feedPressureKpa:c.feedPressureKpa,activeCyclones:c.activeCyclones,distribution:{feed:weibullFractions(c.feedF80Um),mill:normalized(d.millOut),UF:normalized(d.cyc.uf),OF:normalized(d.cyc.of)},status:s.status||'ARRANQUE'};}
function addState(s,k,h){return{t:s.t,millMass:s.millMass.map((v,i)=>Math.max(EPS,v+h*k.dMillMass[i])),millWater:Math.max(EPS,s.millWater+h*k.dMillWater),sumpMass:s.sumpMass.map((v,i)=>Math.max(EPS,v+h*k.dSumpMass[i])),sumpWater:Math.max(EPS,s.sumpWater+h*k.dSumpWater),pumpIntegral:(s.pumpIntegral||0)+h*k.dPumpIntegral,stableFor:s.stableFor,status:s.status};}
function rk4Step(s,c,dtSec){const h=dtSec/60,k1=flowModel(s,c),k2=flowModel(addState(s,k1,h/2),c),k3=flowModel(addState(s,k2,h/2),c),k4=flowModel(addState(s,k3,h),c);s.millMass=s.millMass.map((v,i)=>Math.max(EPS,v+h*(k1.dMillMass[i]+2*k2.dMillMass[i]+2*k3.dMillMass[i]+k4.dMillMass[i])/6));s.millWater=Math.max(EPS,s.millWater+h*(k1.dMillWater+2*k2.dMillWater+2*k3.dMillWater+k4.dMillWater)/6);s.sumpMass=s.sumpMass.map((v,i)=>Math.max(EPS,v+h*(k1.dSumpMass[i]+2*k2.dSumpMass[i]+2*k3.dSumpMass[i]+k4.dSumpMass[i])/6));s.sumpWater=Math.max(EPS,s.sumpWater+h*(k1.dSumpWater+2*k2.dSumpWater+2*k3.dSumpWater+k4.dSumpWater)/6);s.pumpIntegral=(s.pumpIntegral||0)+h*(k1.dPumpIntegral+2*k2.dPumpIntegral+2*k3.dPumpIntegral+k4.dPumpIntegral)/6;s.t+=h;}
function updateStability(s,c,prev,dt){const n=metrics(s,c),t=c.tolerances,r={p:Math.abs(n.P80_OF-prev.P80_OF)/dt,cl:Math.abs(n.CL-prev.CL)/dt,M:Math.abs(n.M_mill-prev.M_mill)/dt,level:Math.abs(n.sumpLevelPct-prev.sumpLevelPct)/dt,rho:Math.abs(n.densityCyclone-prev.densityCyclone)/dt,uf:Math.abs(n.F_UF-prev.F_UF)/dt},stable=r.p<t.p80Rate&&r.cl<t.clRate&&r.M<t.inventoryRate&&r.level<t.levelRate&&r.rho<t.densityRate&&r.uf<t.ufRate&&Math.abs(n.systemSolidsResidual)<t.solids&&Math.abs(n.systemWaterResidual)<t.water;s.stableFor=stable?(s.stableFor||0)+dt:0;s.status=s.stableFor>=c.stabilityWindowMin?'ESTADO ESTACIONARIO':s.t<.5?'ARRANQUE':stable?'ESTABILIZANDO':'TRANSITORIO';return n;}
function advance(s,c,seconds,maxStepSec=1){validateConfig(c);let rem=seconds,prev=metrics(s,c),elapsed=0;while(rem>EPS){const h=Math.min(Math.max(.02,maxStepSec),rem);rk4Step(s,c,h);rem-=h;elapsed+=h;if(elapsed>=6-EPS||rem<=EPS){prev=updateStability(s,c,prev,elapsed/60);elapsed=0;}}return metrics(s,c);}
function initialSump(c,coarse=false){const V=c.sumpVolumeM3*c.sumpInitialLevelPct/100,sp=coarse?8:35,rho=pulpProperties(sp,100-sp,c.oreDensityTpm3).density,total=V*rho,solids=total*sp/100,frac=weibullFractions(coarse?c.feedF80Um*.8:c.d50cBaseUm*8);return{sumpMass:frac.map(x=>x*solids),sumpWater:total-solids};}
function startupState(c){c=defaultConfig(c);validateConfig(c);const frac=weibullFractions(c.feedF80Um*.75,1.05),M=Math.max(1,c.initialMillSolidsT*.18),sp=initialSump(c,true);return{t:0,millMass:frac.map(x=>x*M),millWater:M*.25,sumpMass:sp.sumpMass,sumpWater:sp.sumpWater,pumpIntegral:0,stableFor:0,status:'ARRANQUE'};}
function solveSteadyState(c){c=defaultConfig(c);let s=startupState(c),last=metrics(s,c),converged=false,it=0;for(it=0;it<21600;it++){advance(s,c,5,1);if(it%12===11){const m=metrics(s,c),e=Math.max(Math.abs(m.solidsInventoryRate),Math.abs(m.waterInventoryRate),Math.abs(m.P80_OF-last.P80_OF),Math.abs(m.sumpLevelPct-last.sumpLevelPct));last=m;if(e<1e-3){converged=true;break;}}}s.status=converged?'ESTADO ESTACIONARIO':'TRANSITORIO';s.stableFor=converged?c.stabilityWindowMin:0;return{state:s,metrics:metrics(s,c),converged,iterations:it+1};}
function cloneState(s){return{t:s.t,millMass:s.millMass.slice(),millWater:s.millWater,sumpMass:s.sumpMass.slice(),sumpWater:s.sumpWater,pumpIntegral:s.pumpIntegral||0,stableFor:s.stableFor||0,status:s.status};}
return{SIZES_UM,RHO_WATER,defaultConfig,validateConfig,weibullFractions,cumulativePassing,p80FromFractions,bondEnergy,pulpProperties,moistureWaterTph,effectiveD50,partitionToUF,classify,flowModel,metrics,advance,startupState,solveSteadyState,cloneState};
});
