'use strict';
const E=require('./engine.js'),fs=require('fs');
const results=[],EPS=1e-12,c=E.defaultConfig();
const core=['P80_OF','P80_mill','CL','sumpLevelPct','densityCyclone','F_UF','F_OF','M_mill','Power_mill'];
const driftKeys=[...core,'millWaterMassT','sumpWaterMassT'];
function check(name,expected,calculated,tolerance,units='',details){const error=Math.abs(calculated-expected),pass=Number.isFinite(calculated)&&error<=tolerance;results.push({name,pass,expected,calculated,error,tolerance,units,...(details?{details}:{})});return pass;}
function truth(name,value,details){return check(name,1,value?1:0,0,'',details);}
function rel(a,b){return Math.abs(a-b)/Math.max(Math.abs(a),EPS);}
function finite(o,keys){return keys.every(k=>Number.isFinite(o[k]));}
function pick(m,keys=core){return Object.fromEntries(keys.map(k=>[k,m[k]]));}
function compare(prefix,a,b,keys=core,tol=1e-6){for(const k of keys)check(`${prefix}_${k}`,0,rel(a[k],b[k]),tol,'relative');}
function trace(s,cc,minutes,sampleSec=10,dt=1){const out=[],startMin=s.t;for(let sec=0;sec<minutes*60-EPS;sec+=sampleSec){E.advance(s,cc,Math.min(sampleSec,minutes*60-sec),dt);out.push({...E.metrics(s,cc),t:s.t-startMin});}return out;}
function stats(samples,key,y0,yss){const delta=yss-y0,den=Math.max(Math.abs(delta),EPS),direction=Math.sign(delta)||1,times={};for(const f of [.63,.90,.95,.99]){const hit=samples.find(x=>direction*(x[key]-y0)/den>=f);times[`T${Math.round(f*100)}`]=hit?hit.t:null;}let lo=samples[0],hi=samples[0];for(const x of samples){if(x[key]<lo[key])lo=x;if(x[key]>hi[key])hi=x;}const directed=direction>0?hi[key]:lo[key],opposite=direction>0?lo[key]:hi[key];return{...times,initial:y0,steadyState:yss,minimum:lo[key],timeMinimumMin:lo.t,maximum:hi[key],timeMaximumMin:hi.t,overshoot:Math.max(0,direction*(directed-yss)),undershoot:Math.max(0,-direction*(opposite-y0))};}
function tol(key,m){return({P80_OF:1,P80_mill:2,CL:1,sumpLevelPct:.2,densityCyclone:.01,F_UF:.5,F_OF:.2,M_mill:.5})[key]??Math.max(Math.abs(m[key])*.01,1e-6);}

const solved=E.solveSteadyState(c),ss=solved.metrics;
truth('test_steady_state_convergence',solved.converged,{iterations:solved.iterations,timeMin:solved.state.t});
for(const [name,value] of Object.entries({test_solids_balance:ss.systemSolidsResidual,test_water_balance:ss.systemWaterResidual,test_mill_water_balance:ss.R_water_mill,test_sump_water_balance:ss.R_water_sump,test_cyclone_water_balance:ss.R_water_cyclone,test_cyclone_solids_balance:ss.R_cyclone}))check(name,0,value,1e-8,'t/h');
check('test_circulating_load',ss.F_UF/c.freshSolidsTph*100,ss.CL,1e-9,'%');check('test_steady_product_equals_fresh',ss.F_fresh,ss.F_OF,.01,'t/h');
const pp=E.pulpProperties(60,40,2.7);check('test_pulp_density',100/(60/2.7+40),pp.density,1e-12,'t/m3');check('test_solids_percentage',60,pp.solidsPct,1e-12,'%');check('test_pulp_volumetric_flow',60/2.7+40,pp.volumeM3,1e-12,'m3/h');

// Population balance and empirical/calibrable grinding kinetics.
const psds={coarse:[1,...Array(19).fill(0)],intermediate:E.weibullFractions(1000),fine:[...Array(19).fill(0),1],extreme:[.999,...Array(18).fill(0),.001]};
for(const [name,p] of Object.entries(psds)){const b=E.breakageTransfer(p.map(x=>100*x),1500,c);check(`test_breakage_mass_conservation_${name}`,0,b.transfer.reduce((a,x)=>a+x,0),1e-12,'t/min');truth(`test_breakage_finite_nonnegative_rates_${name}`,b.rates.every(x=>Number.isFinite(x)&&x>=0));}
const rb=E.breakageRates(1000,100,c),rp=E.breakageRates(1500,100,c),rw=E.breakageRates(1000,100,E.defaultConfig({...c,wiKwhT:17})),rz=E.breakageRates(0,100,c),rl=E.breakageRates(1000,10,c);
truth('test_breakage_power_monotonic',rp.every((x,i)=>x>=rb[i]));truth('test_breakage_Wi_monotonic',rw.every((x,i)=>x<=rb[i]));check('test_breakage_zero_power',0,Math.max(...rz),1e-15,'1/min');truth('test_breakage_low_inventory_finite',rl.every(Number.isFinite));truth('test_breakage_size_dependence',rb.every((x,i)=>i===0||x<=rb[i-1]));

// P80 interpolation, boundaries, zeros and normalization.
const known=E.weibullFractions(150,1.2);check('test_p80_weibull_known',150,E.p80FromFractions(known),1e-9,'um');check('test_p80_non_normalized',E.p80FromFractions(known),E.p80FromFractions(known.map(x=>37*x)),1e-10,'um');
for(const [name,p] of Object.entries({coarse:psds.coarse,fine:psds.fine,monodisperse:[...Array(9).fill(0),1,...Array(10).fill(0)],zeros:Array(20).fill(0),sparse:[.2,0,0,0,.3,0,0,0,0,.5,...Array(10).fill(0)]})){const v=E.p80FromFractions(p);truth(`test_p80_${name}_finite_and_bounded`,Number.isFinite(v)&&v>=E.SIZES_UM.at(-1)&&v<=E.SIZES_UM[0],{value:v});}

// Cyclone solids/water closure and bounded monotone partition.
const cs=E.weibullFractions(800).map(x=>2*x),cp=E.pulpProperties(120,80,c.oreDensityTpm3),cy=E.classify(cs,1.25,c,cp,250),partition=E.SIZES_UM.map(d=>E.partitionToUF(d,c,cy.d50));
truth('test_partition_monotonicity',partition.every((x,i,a)=>i===0||x<=a[i-1]));truth('test_partition_bounds',partition.every(x=>x>=0&&x<=1&&Number.isFinite(x)));check('test_cyclone_classwise_mass_conservation',0,Math.max(...cs.map((x,i)=>Math.abs(x-cy.uf[i]-cy.of[i]))),1e-14,'t/min');check('test_cyclone_global_mass_conservation',cy.F_cyclone,cy.F_UF+cy.F_OF,1e-12,'t/min');check('test_cyclone_water_conservation',1.25,cy.waterUF+cy.waterOF,1e-12,'t/min');
for(const [name,changes] of Object.entries({lowSplit:{apexDiameterMm:30,cycloneBypassPct:0},highSplit:{apexDiameterMm:250,cycloneBypassPct:80}})){const cc=E.defaultConfig({...c,...changes}),x=E.classify(cs,1.25,cc,cp,250);truth(`test_cyclone_water_${name}_physical`,x.waterRecovery>=0&&x.waterRecovery<=1&&x.waterUF>=0&&x.waterOF>=0&&[x.waterRecovery,x.waterUF,x.waterOF].every(Number.isFinite));}
for(const [name,changes] of Object.entries({pressure:{feedPressureKpa:110},cyclones:{activeCyclones:5},apex:{apexDiameterMm:110},vortex:{vortexFinderDiameterMm:190},density:{oreDensityTpm3:3}})){const cc=E.defaultConfig({...c,...changes}),v=E.effectiveD50(cc,E.pulpProperties(120,80,cc.oreDensityTpm3),250);truth(`test_cyclone_${name}_response_finite`,Number.isFinite(v)&&v>=.45*cc.d50cBaseUm&&v<=2.2*cc.d50cBaseUm,{d50:v});}

// Sump identities, nonnegative inventory, pump limits and anti-windup.
for(const level of [5,10,50,90,99]){const cc=E.defaultConfig({...c,sumpInitialLevelPct:level}),s=E.startupState(cc),m=E.metrics(s,cc);check(`test_sump_initial_level_${level}`,level,m.sumpLevelPct,1e-10,'%');check(`test_sump_volume_identity_${level}`,m.sumpSolidsMassT/cc.oreDensityTpm3+m.sumpWaterMassT,m.sumpVolumeM3,1e-10,'m3');}
const severeC=E.defaultConfig({...c,sumpInitialLevelPct:5,pumpControlMode:'manual',pumpSpeedPct:100,sumpWaterM3h:0}),severe=E.startupState(severeC);trace(severe,severeC,30,1,.25);truth('test_no_negative_sump_inventory',severe.sumpWater>=0&&severe.sumpMass.every(x=>x>=0)&&finite(E.metrics(severe,severeC),driftKeys));
for(const [name,level,integral] of [['high',99,200],['low',5,-200]]){const cc=E.defaultConfig({...c,sumpInitialLevelPct:level}),s=E.startupState(cc);s.pumpIntegral=integral;const d=E.flowModel(s,cc);truth(`test_pump_${name}_bounds`,d.effectiveSpeed>=0&&d.effectiveSpeed<=100);check(`test_pump_${name}_anti_windup`,0,d.dPumpIntegral,1e-12);}
const ws=E.cloneState(solved.state);ws.sumpWater*=1.5;const wsInitial=E.metrics(ws,c),wsFinal=trace(ws,c,120,10,1).at(-1);truth('test_pump_sump_water_plus_50_no_divergence',finite(wsFinal,driftKeys)&&wsFinal.sumpLevelPct>=0&&wsFinal.sumpLevelPct<100&&Math.abs(wsFinal.sumpLevelPct-c.sumpLevelSetpointPct)<Math.abs(wsInitial.sumpLevelPct-c.sumpLevelSetpointPct),{initialLevel:wsInitial.sumpLevelPct,finalLevel:wsFinal.sumpLevelPct,finalStatus:wsFinal.status});

// Manual/auto mill-water control, bounds, direction and anti-windup.
const ac=E.defaultConfig({...c,millWaterControlMode:'auto'}),hs=E.cloneState(solved.state),ls=E.cloneState(solved.state);hs.millWater*=.3;ls.millWater*=3;const hc=E.flowModel(hs,ac),lc=E.flowModel(ls,ac);
truth('test_mill_water_high_solids_reaction',hc.freshMillWaterM3h>lc.freshMillWaterM3h);truth('test_mill_water_controller_bounds',[hc,lc].every(x=>x.freshMillWaterM3h>=ac.millWaterMinimumM3h&&x.freshMillWaterM3h<=ac.millWaterMaximumM3h));hs.millWaterIntegral=1e6;ls.millWaterIntegral=-1e6;check('test_mill_water_high_anti_windup',0,E.flowModel(hs,ac).dMillWaterIntegral,1e-12);check('test_mill_water_low_anti_windup',0,E.flowModel(ls,ac).dMillWaterIntegral,1e-12);const autoFinal=trace(E.cloneState(solved.state),ac,180,10,1).at(-1);truth('test_mill_water_auto_no_divergence',finite(autoFinal,driftKeys)&&autoFinal.sumpLevelPct<100);

// Startup response. Measure to 600 min, but acceptance remains 360 min = 72 controller integral times; require 5 min sustained tolerance.
const startup=E.startupState(c),startup0=E.metrics(startup,c),startupTrace=trace(startup,c,600,10,1),startupFinal=startupTrace.at(-1),startupKeys=['P80_OF','CL','sumpLevelPct','densityCyclone','M_mill'],startupStats=Object.fromEntries(startupKeys.map(k=>[k,stats(startupTrace,k,startup0[k],ss[k])])),startupCompare=['P80_OF','CL','sumpLevelPct','densityCyclone','F_UF'];
const within=m=>startupCompare.every(k=>Math.abs(m[k]-ss[k])<=tol(k,ss));let startupConvergenceTimeMin=null,insideSec=0;for(const m of startupTrace){insideSec=within(m)?insideSec+10:0;if(insideSec>=300){startupConvergenceTimeMin=m.t-5;break;}}
for(const k of startupCompare)check(`test_startup_convergence_${k}`,ss[k],startupFinal[k],tol(k,ss),k);truth('test_startup_reasonable_time',startupConvergenceTimeMin!==null&&startupConvergenceTimeMin<=360,{convergenceTimeMin:startupConvergenceTimeMin,reasonableLimitMin:360,measurementHorizonMin:600,sustainedWindowMin:5});

// Relative drift from exactly the computed SS.
const noDrift={},ds=E.cloneState(solved.state);let prior=0;for(const minutes of [30,60,120]){E.advance(ds,c,(minutes-prior)*60,1);prior=minutes;const m=E.metrics(ds,c),errors=Object.fromEntries(driftKeys.map(k=>[k,rel(ss[k],m[k])]));noDrift[`${minutes}min`]={metrics:pick(m,driftKeys),relativeErrors:errors,maxRelativeDrift:Math.max(...Object.values(errors))};truth(`test_no_drift_${minutes}min`,Object.values(errors).every(x=>x<=1e-4),{maxRelativeDrift:noDrift[`${minutes}min`].maxRelativeDrift});}

// Solver timestep independence over the same 90 min transient.
const dtIndependence={referenceDtSec:.1,cases:{}},dr=E.startupState(c);E.advance(dr,c,90*60,.1);const drm=E.metrics(dr,c);for(const dt of [.5,1,2]){const s=E.startupState(c);E.advance(s,c,90*60,dt);const m=E.metrics(s,c);dtIndependence.cases[dt]=pick(m);compare(`test_dt_independence_${dt}s`,drm,m,core,1e-5);}

// Testable simulation clock. Wall time and render cadence genuinely differ.
function clockRun(speed,fps,target=1800){const s=E.startupState(c),wallTarget=target/speed,frame=1/fps;let wall=0,calls=0,last;while(wall<wallTarget-EPS){const d=Math.min(frame,wallTarget-wall);last=E.advanceClock(s,c,{wallDeltaSec:d,speedMultiplier:speed,solverMaxDtSec:1});wall+=d;calls++;}return{speed,fps,wallTimeSec:wall,simTimeSec:s.t*60,solverMaxDtSec:1,renderIntervalSec:frame,renderCalls:calls,lastSimDeltaSec:last.simDeltaSec,metrics:E.metrics(s,c)};}
const speedIndependence={targetSimTimeSec:1800,cases:{}},speedCases=[1,5,10,20].map(x=>clockRun(x,30)),sr=speedCases[0].metrics;for(const x of speedCases){speedIndependence.cases[`${x.speed}x`]={wallTimeSec:x.wallTimeSec,simTimeSec:x.simTimeSec,solverMaxDtSec:x.solverMaxDtSec,renderIntervalSec:x.renderIntervalSec,renderCalls:x.renderCalls,metrics:pick(x.metrics)};check(`test_speed_clock_${x.speed}x_wall_relation`,1800/x.speed,x.wallTimeSec,1e-8,'s');check(`test_speed_clock_${x.speed}x_sim_target`,1800,x.simTimeSec,1e-6,'s');compare(`test_speed_independence_${x.speed}x`,sr,x.metrics,core,2e-5);}
const renderIndependence={speedMultiplier:20,targetSimTimeSec:1800,cases:{}},renderCases=[30,60,120].map(fps=>clockRun(20,fps)),rr=renderCases[0].metrics;for(const x of renderCases){renderIndependence.cases[`${x.fps}fps`]={renderIntervalSec:x.renderIntervalSec,renderCalls:x.renderCalls,metrics:pick(x.metrics)};compare(`test_render_independence_${x.fps}fps`,rr,x.metrics,core,2e-5);}

// Long external conservation, absolute residual and relative to accumulated input throughput.
function conservationAudit(minutes){const s=E.cloneState(solved.state),before=E.metrics(s,c),iS=before.M_mill+before.sumpSolidsMassT,iW=before.millWaterMassT+before.sumpWaterMassT,inS=c.freshSolidsTph,inW=c.millWaterM3h+c.sumpWaterM3h+E.moistureWaterTph(c);let outS=0,outW=0,prev=before;for(let sec=0;sec<minutes*60;sec+=2){const h=Math.min(2,minutes*60-sec);E.advance(s,c,h,1);const now=E.metrics(s,c);outS+=(prev.F_OF+now.F_OF)/2*h/3600;outW+=(prev.W_OF+now.W_OF)/2*h/3600;prev=now;}const after=E.metrics(s,c),solidResidual=inS*minutes/60-outS-(after.M_mill+after.sumpSolidsMassT-iS),waterResidual=inW*minutes/60-outW-(after.millWaterMassT+after.sumpWaterMassT-iW),pS=inS*minutes/60,pW=inW*minutes/60;return{minutes,solidResidualT:solidResidual,waterResidualT:waterResidual,solidRelativeError:Math.abs(solidResidual)/Math.max(pS,EPS),waterRelativeError:Math.abs(waterResidual)/Math.max(pW,EPS),solidProcessedT:pS,waterProcessedT:pW};}
const conservation={};for(const minutes of [10,60,240]){const x=conservationAudit(minutes);conservation[`${minutes}min`]=x;truth(`test_long_conservation_${minutes}min_solids`,x.solidRelativeError<=1e-6,x);truth(`test_long_conservation_${minutes}min_water`,x.waterRelativeError<=1e-6,x);}

// Perturbations: full ranges, T95, overshoot and final status.
function perturbation(name,changes,minutes=240){const cc=E.defaultConfig({...c,...changes}),s=E.cloneState(solved.state),initial=E.metrics(s,c);s.status='TRANSITORIO';s.stableFor=0;const samples=trace(s,cc,minutes,20,1),final=samples.at(-1),keys=['P80_OF','CL','sumpLevelPct','densityCyclone','F_UF','F_OF'],response=Object.fromEntries(keys.map(k=>[k,stats(samples,k,initial[k],final[k])]));return{name,changes,initial:pick(initial,keys),minimum:Object.fromEntries(keys.map(k=>[k,response[k].minimum])),maximum:Object.fromEntries(keys.map(k=>[k,response[k].maximum])),final:pick(final,keys),T95:Object.fromEntries(keys.map(k=>[k,response[k].T95])),overshoot:Object.fromEntries(keys.map(k=>[k,response[k].overshoot])),steadyStateStatus:final.status,finite:finite(final,driftKeys)};}
const perturbations=[perturbation('water_mill_60_to_80',{millWaterM3h:80}),perturbation('water_sump_20_to_40',{sumpWaterM3h:40}),perturbation('pump_speed_70_to_90',{pumpSpeedPct:90}),perturbation('active_cyclones_6_to_5',{activeCyclones:5}),perturbation('pressure_100_to_120',{feedPressureKpa:120}),perturbation('Wi_14_to_17',{wiKwhT:17}),perturbation('feed_100_to_120',{freshSolidsTph:120})];for(const p of perturbations){truth(`test_perturbation_${p.name}_finite`,p.finite);truth(`test_perturbation_${p.name}_measurable_response`,Object.keys(p.final).some(k=>rel(p.initial[k],p.final[k])>1e-4),{status:p.steadyStateStatus,T95:p.T95});}

// Operating-regime-aware Wi comparison, capacity predicted by current model, and ±10% sensitivity.
function scenario(changes){const cc=E.defaultConfig({...c,...changes}),x=E.solveSteadyState(cc);return{config:cc,solved:x,metrics:x.metrics};}
const energyBase=E.grindingEnergyModel(solved.state.millMass,E.flowModel(solved.state,c).millOut,c),energyScaled=E.grindingEnergyModel(solved.state.millMass.map(x=>x*2),E.flowModel(solved.state,c).millOut.map(x=>x*2),c);
truth('test_energy_components_finite',[energyBase.P_available,energyBase.P_required,energyBase.P_used,energyBase.energyAvailability].every(Number.isFinite));truth('test_energy_availability_bounds',energyBase.energyAvailability>=0&&energyBase.energyAvailability<=1&&energyScaled.energyAvailability>=0&&energyScaled.energyAvailability<=1);check('test_energy_used_is_min',Math.min(energyScaled.P_available,energyScaled.P_required),energyScaled.P_used,1e-9,'kW');truth('test_energy_demand_scales_with_breakage_mass',Math.abs(energyScaled.P_required/energyBase.P_required-2)<1e-9);truth('test_energy_limitation_reduces_rates',energyScaled.energyLimited&&energyScaled.effectiveRates.every((x,i)=>x<=energyScaled.baseRates[i]));
const w17=scenario({wiKwhT:17}),wkeys=['P80_OF','Power_mill','specificEnergy','M_mill','CL'],wiRegime={Wi14:{converged:solved.converged,...pick(ss,wkeys)},Wi17:{converged:w17.solved.converged,...pick(w17.metrics,wkeys)},availablePowerKw:c.installedPowerKw*c.mechanicalEfficiencyPct/100};wiRegime.powerLimited14=wiRegime.Wi14.Power_mill>=.99*wiRegime.availablePowerKw;wiRegime.powerLimited17=wiRegime.Wi17.Power_mill>=.99*wiRegime.availablePowerKw;truth('test_Wi_scenarios_converged',wiRegime.Wi14.converged&&wiRegime.Wi17.converged);truth('test_Wi_harder_ore_not_finer',wiRegime.Wi17.P80_OF>=wiRegime.Wi14.P80_OF-1e-6,wiRegime);
const millCapacity=[];for(const feed of [50,100,150,200]){const x=scenario({freshSolidsTph:feed}),m=x.metrics;millCapacity.push({feedTph:feed,processFeasible:x.solved.converged,feasibilityStatus:x.solved.feasibilityStatus,operatingStatus:m.operatingStatus,capacityFlags:m.capacityFlags,P_available:m.P_available,P_required:m.P_required,P_used:m.P_used,P80_OF:m.P80_OF,M_mill:m.M_mill,CL:m.CL,energyAvailability:m.energyAvailability});}truth('test_mill_capacity_scenarios_finite',millCapacity.every(x=>Object.values(x).filter(v=>typeof v==='number').every(Number.isFinite)));for(const x of millCapacity)truth(x.feedTph<=100?`test_mill_capacity_${x.feedTph}tph_feasible`:`test_mill_capacity_${x.feedTph}tph_hydraulic_detector`,x.feedTph<=100?x.processFeasible:x.capacityFlags.HYDRAULIC_CAPACITY_EXCEEDED,{processFeasible:x.processFeasible,feasibilityStatus:x.feasibilityStatus,operatingStatus:x.operatingStatus});
const sensitivity={base:pick(ss,['P80_OF','CL','Power_mill','densityCyclone','sumpLevelPct']),cases:[]},inputs={Wi:'wiKwhT',feed:'freshSolidsTph',power:'installedPowerKw',millWater:'millWaterM3h',pressure:'feedPressureKpa',d50Base:'d50cBaseUm'};for(const [label,key] of Object.entries(inputs))for(const factor of [.9,1.1]){const x=scenario({[key]:c[key]*factor}),outputs=pick(x.metrics,['P80_OF','CL','Power_mill','densityCyclone','sumpLevelPct']),changesPct=Object.fromEntries(Object.keys(outputs).map(k=>[k,100*(outputs[k]-ss[k])/Math.max(Math.abs(ss[k]),EPS)]));sensitivity.cases.push({parameter:label,factor,inputValue:c[key]*factor,converged:x.solved.converged,outputs,changesPct});}truth('test_sensitivity_finite_and_converged',sensitivity.cases.every(x=>x.converged&&Object.values(x.outputs).every(Number.isFinite)));

const startupJson={T63:{},T90:{},T95:{},T99:{},responses:startupStats,convergenceTimeMin:startupConvergenceTimeMin,reasonableLimitMin:360,measurementHorizonMin:600,sustainedToleranceWindowMin:5,final:pick(startupFinal,startupCompare)};for(const [key,x] of Object.entries(startupStats))for(const t of ['T63','T90','T95','T99'])startupJson[t][key]=x[t];
const passed=results.filter(x=>x.pass).length,failed=results.length-passed,report={generatedAt:new Date().toISOString(),summary:{passed,failed,total:results.length,allPassed:failed===0},steadyState:{converged:solved.converged,iterations:solved.iterations,timeMin:solved.state.t,metrics:ss},startup:startupJson,speedIndependence,renderIndependence,dtIndependence,noDrift,conservation,WiRegime:wiRegime,millCapacity,sensitivity,perturbations,tests:results};fs.writeFileSync('TEST_RESULTS.json',JSON.stringify(report,null,2));results.forEach(x=>console.log(`${x.pass?'PASS':'FAIL'} ${x.name}: expected=${x.expected} calculated=${x.calculated} error=${x.error} tolerance=${x.tolerance} ${x.units}`));console.log(`SUMMARY ${passed}/${results.length} PASS`);process.exitCode=failed?1:0;
