(function(){
'use strict';
const $=id=>document.getElementById(id), num=id=>Number($(id).value);
let config,state,running=false,raf=null,lastWall=null,realElapsed=0;
let hist={t:[],p80m:[],p80of:[],p80uf:[],fresh:[],mill:[],uf:[],of:[],cl:[],M:[],power:[],level:[],rhoCyclone:[],solidsCyclone:[],waterMill:[],waterSump:[],waterOF:[],waterUF:[]};
function cfg(){return MKEngine.defaultConfig({freshSolidsTph:Math.max(.01,num('tph')),feedF80Um:Math.max(1,num('f80')),wiKwhT:Math.max(.01,num('wi')),oreDensityTpm3:Math.max(1.1,num('oreDensity')),feedMoisturePct:Math.max(0,num('feedMoisture')),mechanicalEfficiencyPct:Math.max(1,num('eff')),millVolumeM3:Math.max(1,num('millVol')),initialMillSolidsT:Math.max(1,num('hold0')),tauPSDMin:Math.max(.05,num('tauPSD')),tauHoldMin:Math.max(.05,num('tauHold')),installedPowerKw:Math.max(1,num('installedPower')),millWaterM3h:Math.max(0,num('millWater')),millWaterControlMode:$('millWaterMode').value,millSolidsSetpointPct:Math.min(100,Math.max(0,num('millSolidsSP'))),millWaterMinimumM3h:Math.max(0,num('millWaterMin')),millWaterMaximumM3h:Math.max(1,num('millWaterMax')),millWaterGain:Math.max(.01,num('millWaterKp')),millWaterIntegralTimeMin:Math.max(.1,num('millWaterTi')),ballChargePct:Math.max(0,num('ballCharge')),millSpeedCriticalPct:Math.max(1,num('criticalSpeed')),sumpVolumeM3:Math.max(1,num('sumpVolume')),sumpInitialLevelPct:Math.max(0,num('sumpInitialLevel')),sumpWaterM3h:Math.max(0,num('sumpWater')),sumpLevelSetpointPct:Math.max(0,num('sumpLevelSP')),pumpControlMode:$('pumpMode').value,pumpSpeedPct:Math.max(0,num('pumpSpeed')),pumpMinimumControlPct:Math.max(0,num('pumpMinSpeed')),pumpMaxFlowM3h:Math.max(1,num('pumpMaxFlow')),pumpLevelGain:Math.max(.01,num('pumpKp')),pumpIntegralTimeMin:Math.max(.1,num('pumpTi')),d50cBaseUm:Math.max(1,num('d50')),cycloneImperfection:Math.max(.05,num('imperfection')),cycloneBypassPct:Math.max(0,num('bypass')),cycloneDiameterMm:Math.max(1,num('cycloneDiameter')),activeCyclones:Math.max(1,Math.round(num('activeCyclones'))),feedPressureKpa:Math.max(20,num('cyclonePressure')),apexDiameterMm:Math.max(1,num('apexDiameter')),vortexFinderDiameterMm:Math.max(1,num('vortexDiameter')),tauCycloneMin:Math.max(.01,num('tauCyclone'))});}
function resetHistory(){hist=Object.fromEntries(Object.keys(hist).map(k=>[k,[]]));record();}
function metric(){return MKEngine.metrics(state,config);}
function record(){const m=metric();hist.t.push(m.t);hist.p80m.push(m.P80_mill);hist.p80of.push(m.P80_OF);hist.p80uf.push(m.P80_UF);hist.fresh.push(m.F_fresh);hist.mill.push(m.F_mill);hist.uf.push(m.F_UF);hist.of.push(m.F_OF);hist.cl.push(m.CL);hist.M.push(m.M_mill);hist.power.push(m.Power_mill);hist.level.push(m.sumpLevelPct);hist.rhoCyclone.push(m.densityCyclone);hist.solidsCyclone.push(m.solidsPctCyclone);hist.waterMill.push(m.W_mill_fresh);hist.waterSump.push(config.sumpWaterM3h);hist.waterOF.push(m.W_OF);hist.waterUF.push(m.W_UF);if(hist.t.length>1800)Object.values(hist).forEach(a=>a.shift());}
function stop(){running=false;if(raf)cancelAnimationFrame(raf);raf=null;lastWall=null;realElapsed=0;}
function calculate(){stop();config=cfg();const solved=MKEngine.solveSteadyState(config);state=solved.state;state.t=0;state.status=solved.converged?'ESTADO ESTACIONARIO':'TRANSITORIO';resetHistory();update();drawAll();}
function startup(){stop();config=cfg();state=MKEngine.startupState(config);resetHistory();start();}
function start(){if(running)return;running=true;lastWall=null;raf=requestAnimationFrame(loop);update();}
function loop(now){if(!running)return;if(lastWall===null){lastWall=now;raf=requestAnimationFrame(loop);return;}let wall=Math.min(2,Math.max(0,(now-lastWall)/1000));lastWall=now;realElapsed+=wall;MKEngine.advanceClock(state,config,{wallDeltaSec:wall,speedMultiplier:Math.max(.01,num('speed')),solverMaxDtSec:Math.max(.02,num('dt'))});const sumpTrip=metric().sumpLevelPct>=100;if(sumpTrip){state.sumpHighTrip=true;running=false;raf=null;lastWall=null;realElapsed=0;}record();update();drawAll();if(sumpTrip)return;raf=requestAnimationFrame(loop);}
function setText(id,v){if($(id))$(id).textContent=v;}
function update(){const m=metric(),util=100*m.Power_mill/Math.max(1,config.installedPowerKw),status=m.status,sumpTrip=Boolean(state.sumpHighTrip)||m.sumpLevelPct>=100,sumpWarning=m.sumpLevelPct>=80;
 setText('kBond',MKEngine.bondEnergy(config.wiKwhT,config.feedF80Um,m.P80_OF).toFixed(3));setText('kPower',m.Power_mill.toFixed(0));setText('kP80',m.P80_OF.toFixed(1));setText('kP80Mill',m.P80_mill.toFixed(1));setText('kCL',m.CL.toFixed(0));
 setText('svgFeed',`Sólidos: ${m.F_fresh.toFixed(1)} t/h`);setText('svgFeed2',`F80: ${m.P80_feed.toFixed(0)} µm · Wi: ${config.wiKwhT.toFixed(1)} kWh/t`);
 setText('svgMill',`Sólidos: ${m.F_mill.toFixed(1)} t/h`);setText('svgMill2',`Agua: ${m.W_mill_out.toFixed(1)} m³/h`);setText('svgMill3',`w/w = ${m.solidsPctMillOut.toFixed(1)} % · P80: ${m.P80_mill.toFixed(0)} µm`);
 setText('svgPower',`Potencia: ${m.Power_mill.toFixed(0)} kW\nw/w actual = ${m.solidsPctMillInventory.toFixed(1)} % · SP = ${config.millSolidsSetpointPct.toFixed(1)} %`);setText('svgPower2',`MODO: ${config.millWaterControlMode==='auto'?'AUTOMÁTICO':'MANUAL'}${m.millWaterSaturated?' · LÍMITE':''}\nFresca: ${m.W_mill_fresh.toFixed(1)} · UF: ${m.W_mill_recycle.toFixed(1)} · Humedad: ${m.W_mill_moisture.toFixed(1)} m³/h\nTotal: ${m.W_mill_in.toFixed(1)} m³/h`);document.querySelector('.mill-power-card').classList.toggle('water-saturated',m.millWaterSaturated);
 setText('svgSump',`Nivel: ${m.sumpLevelPct.toFixed(1)}% · SP: ${config.sumpLevelSetpointPct.toFixed(1)}%`);setText('svgSump2',`Volumen: ${m.sumpVolumeM3.toFixed(1)} m³\nw/w = ${m.solidsPctSump.toFixed(1)} %`);setText('svgSumpAlarm',sumpTrip?'PARADA: NIVEL ≥ 100%':sumpWarning?'ALARMA: NIVEL ≥ 80%':'');const sumpGauge=$('sumpGauge'),gaugeLevel=Math.max(0,Math.min(100,m.sumpLevelPct));sumpGauge.style.setProperty('--level',`${gaugeLevel}%`);sumpGauge.style.setProperty('--sp',`${Math.max(0,Math.min(100,config.sumpLevelSetpointPct))}%`);sumpGauge.setAttribute('aria-valuenow',m.sumpLevelPct.toFixed(1));setText('sumpGaugeValue',`${m.sumpLevelPct.toFixed(0)}%`);$('sumpCard').classList.toggle('sump-low',m.sumpLevelPct<10);$('sumpCard').classList.toggle('sump-warning',sumpWarning&&!sumpTrip);$('sumpCard').classList.toggle('sump-trip',sumpTrip);
 const atMax=m.pumpSpeedEffectivePct>=99.95,atMin=m.pumpSpeedEffectivePct<=config.pumpMinimumControlPct+.05,pumpSaturated=atMax||atMin,mode=config.pumpControlMode==='auto'?'AUTO':'MANUAL';setText('svgPump',`${mode} · Velocidad: ${m.pumpSpeedEffectivePct.toFixed(0)}%${atMax?' · MÁX':atMin?' · MÍN':''}`);setText('svgPump2',`Caudal: ${m.Q_pump.toFixed(0)} m³/h`);$('pumpCard').classList.toggle('pump-saturated',pumpSaturated);
 setText('svgCyclone',`Sólidos: ${m.F_cyclone.toFixed(1)} t/h`);setText('svgCyclone2',`Agua: ${m.W_cyclone.toFixed(1)} m³/h`);setText('svgCyclone3',`w/w = ${m.solidsPctCyclone.toFixed(1)} % · P80: ${m.P80_cyclone.toFixed(0)} µm`);setText('svgCyclone4','');
 setText('svgProduct',`Sólidos: ${m.F_OF.toFixed(1)} t/h`);setText('svgProduct2',`Agua: ${m.W_OF.toFixed(1)} m³/h`);setText('svgProduct3',`w/w = ${m.solidsPctOF.toFixed(1)} % · P80: ${m.P80_OF.toFixed(0)} µm`);
 setText('svgUF',`Sólidos: ${m.F_UF.toFixed(1)} t/h · Agua: ${m.W_UF.toFixed(1)} m³/h`);setText('svgUF2',`w/w = ${m.solidsPctUF.toFixed(1)} % · P80: ${m.P80_UF.toFixed(0)} µm`);
 setText('stateT',m.t.toFixed(3)+' min');setText('stateM',m.M_mill.toFixed(2)+' t S / '+m.millWaterMassT.toFixed(2)+' t W');setText('stateUtil',util.toFixed(1)+' %');setText('stateUF',m.F_UF.toFixed(2)+' t/h');setText('stateT2',m.t.toFixed(3)+' min');setText('stateM2',m.M_mill.toFixed(2)+' t');setText('stateUtil2',util.toFixed(1)+' %');setText('stateUF2',m.F_UF.toFixed(2)+' t/h');setText('toolbarTime',m.t.toFixed(3)+' min');
 setText('steadyStatus',sumpTrip?'PARADA NIVEL ALTO':status);$('steadyStatus').style.color=sumpTrip?'#d62828':status==='ESTADO ESTACIONARIO'?'#2f7d32':status==='TRANSITORIO'?'#b03a2e':'#c47a00';setText('stateBadge',sumpTrip?'SIMULACIÓN DETENIDA · NIVEL DEL SUMP ≥ 100%':running?(sumpWarning?'ALARMA NIVEL SUMP ≥ 80%':'Simulación en ejecución'):`${status} · Sump ${m.sumpAlarm}`);setText('simStatus',sumpTrip?'PARADA AUTOMÁTICA: nivel del sump alcanzó 100%':running?`${status} · ${num('speed')}× · Sump ${m.sumpLevelPct.toFixed(1)}% (${sumpWarning?'ALARMA ALTA':m.sumpAlarm})`:'Modelo detenido / pausado');
 const vals={vFresh:m.F_fresh,vMill:m.F_mill,vCyclone:m.F_cyclone,vOF:m.F_OF,vUF:m.F_UF,vSplit:100*m.split_UF,vResid:m.systemSolidsResidual,vResidC:m.R_cyclone,vWaterResid:m.systemWaterResidual,vP80UF:m.P80_UF,vSpecific:m.specificEnergy,vSumpLevel:m.sumpLevelPct,vSumpVolume:m.sumpVolumeM3,vCycloneSolids:m.solidsPctCyclone,vCycloneDensity:m.densityCyclone,vPumpFlow:m.Q_pump,vWaterOF:m.W_OF,vWaterUF:m.W_UF};Object.entries(vals).forEach(([id,v])=>setText(id,Number(v).toFixed(id.includes('Resid')?6:2)));
}
function axes(ctx,w,h,min,max,label){ctx.clearRect(0,0,w,h);ctx.font='10px Segoe UI';for(let j=0;j<5;j++){let y=22+j*(h-44)/4;ctx.strokeStyle='#e3e8eb';ctx.beginPath();ctx.moveTo(48,y);ctx.lineTo(w-12,y);ctx.stroke();ctx.fillStyle='#71808a';ctx.fillText((max-(max-min)*j/4).toFixed(0),6,y+3)}ctx.fillText(label,50,13);}
function curve(ctx,xs,ys,w,h,min,max,color){if(xs.length<2)return;let x0=xs[0],xr=Math.max(.001,xs[xs.length-1]-x0);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ys.forEach((v,i)=>{let x=48+(xs[i]-x0)/xr*(w-62),y=22+(max-v)/Math.max(.001,max-min)*(h-44);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();}
function plot(id,series,label){const c=$(id);if(!c)return;const ctx=c.getContext('2d'),all=series.flatMap(s=>s.data).filter(Number.isFinite);let min=Math.min(...all),max=Math.max(...all);if(!all.length){min=0;max=1}if(max-min<1){min-=.5;max+=.5}min=Math.max(0,min*.92);max*=1.08;axes(ctx,c.width,c.height,min,max,label);series.forEach(s=>curve(ctx,hist.t,s.data,c.width,c.height,min,max,s.color));}
function drawAll(){plot('trend',[{data:hist.p80m,color:'#596b75'},{data:hist.p80of,color:'#f28a00'},{data:hist.t.map(()=>num('p80Target')),color:'#2f7eb8'}],'P80 (µm)');plot('flowTrend',[{data:hist.fresh,color:'#2f7eb8'},{data:hist.mill,color:'#596b75'},{data:hist.uf,color:'#f28a00'},{data:hist.of,color:'#1e9b59'}],'Flujo sólidos (t/h)');plot('clTrend',[{data:hist.cl,color:'#f28a00'}],'Carga circulante (%)');plot('inventoryTrend',[{data:hist.M,color:'#2f7eb8'}],'Inventario sólidos (t)');plot('powerTrend',[{data:hist.power,color:'#c8483f'}],'Potencia (kW)');plot('sumpTrend',[{data:hist.level,color:'#45aee9'}],'Nivel sump (%)');plot('pulpTrend',[{data:hist.solidsCyclone,color:'#6f42c1'},{data:hist.rhoCyclone.map(x=>x*40),color:'#1e9b59'}],'Sólidos (w/w %); densidad × 40');plot('waterTrend',[{data:hist.waterMill,color:'#2f7eb8'},{data:hist.waterSump,color:'#45aee9'},{data:hist.waterOF,color:'#1e9b59'},{data:hist.waterUF,color:'#f28a00'}],'Agua (m³/h)');drawPSD();}
function drawPSD(){const c=$('psdChart');if(!c)return;const m=metric(),ctx=c.getContext('2d'),w=c.width,h=c.height,streams=[['feed','#2f7eb8'],['mill','#596b75'],['UF','#f28a00'],['OF','#1e9b59']];axes(ctx,w,h,0,100,'% pasante acumulado');const xs=MKEngine.SIZES_UM.slice().reverse().map(Math.log);streams.forEach(([key,color])=>{const pass=MKEngine.cumulativePassing(m.distribution[key]);curve(ctx,xs,pass.slice().reverse().map(x=>x*100),w,h,0,100,color)});setText('psdP80Feed',m.P80_feed.toFixed(1)+' µm');setText('psdP80Mill',m.P80_mill.toFixed(1)+' µm');setText('psdP80UF',m.P80_UF.toFixed(1)+' µm');setText('psdP80OF',m.P80_OF.toFixed(1)+' µm');const passes=Object.fromEntries(streams.map(([key])=>[key,MKEngine.cumulativePassing(m.distribution[key])]));$('psdTableBody').innerHTML=MKEngine.SIZES_UM.map((size,i)=>`<tr><td>${size.toLocaleString('es-CL')}</td>${streams.map(([key])=>`<td>${(100*m.distribution[key][i]).toFixed(2)}</td><td>${(100*passes[key][i]).toFixed(2)}</td>`).join('')}</tr>`).join('');}
function disturb(key,value){config[key]=value;state.stableFor=0;state.status='TRANSITORIO';update();}
function exportCSV(){const rows=[['time_min','F_fresh_s_tph','F_mill_s_tph','F_UF_s_tph','F_OF_s_tph','P80_mill_um','P80_OF_um','CL_pct','M_mill_s_t','Power_kW','Sump_level_pct','Cyclone_concentration_w_w_pct','Cyclone_density_t_m3','Mill_water_m3h','Sump_water_m3h','OF_water_m3h','UF_water_m3h']];hist.t.forEach((t,i)=>rows.push([t,hist.fresh[i],hist.mill[i],hist.uf[i],hist.of[i],hist.p80m[i],hist.p80of[i],hist.cl[i],hist.M[i],hist.power[i],hist.level[i],hist.solidsCyclone[i],hist.rhoCyclone[i],hist.waterMill[i],hist.waterSump[i],hist.waterOF[i],hist.waterUF[i]]));const blob=new Blob(['\ufeff'+rows.map(r=>r.join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='MK_ProcessSim_historial.csv';a.click();URL.revokeObjectURL(a.href);}
function exportPSDExcel(){const m=metric(),streams=['feed','mill','UF','OF'],passes=Object.fromEntries(streams.map(key=>[key,MKEngine.cumulativePassing(m.distribution[key])])),n=x=>Number(x).toFixed(4).replace('.',','),rows=[['MK ProcessSim - Distribución granulométrica'],['Tiempo simulado',n(m.t),'min'],['Alimentación fresca',n(m.F_fresh),'t/h'],['Feed molino',n(m.F_mill),'t/h'],['Underflow',n(m.F_UF),'t/h'],['Overflow / producto',n(m.F_OF),'t/h'],['Carga circulante',n(m.CL),'%'],[],['P80 alimentación',n(m.P80_feed),'µm'],['P80 descarga molino',n(m.P80_mill),'µm'],['P80 underflow',n(m.P80_UF),'µm'],['P80 overflow / producto',n(m.P80_OF),'µm'],[],['Tamaño [µm]','Alimentación - retenido [%]','Alimentación - pasante acumulado [%]','Descarga molino - retenido [%]','Descarga molino - pasante acumulado [%]','Underflow - retenido [%]','Underflow - pasante acumulado [%]','Overflow / producto - retenido [%]','Overflow / producto - pasante acumulado [%]']];MKEngine.SIZES_UM.forEach((size,i)=>rows.push([size,n(100*m.distribution.feed[i]),n(100*passes.feed[i]),n(100*m.distribution.mill[i]),n(100*passes.mill[i]),n(100*m.distribution.UF[i]),n(100*passes.UF[i]),n(100*m.distribution.OF[i]),n(100*passes.OF[i])]));const csv='\ufeff'+rows.map(r=>r.map(v=>String(v??'').replaceAll(';',',')).join(';')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MK_ProcessSim_granulometria_${m.t.toFixed(2).replace('.', '_')}min.csv`;a.click();URL.revokeObjectURL(a.href);}
function enrich(){const table=$('stateBadge').nextElementSibling;[['Feed fresco sólidos','vFresh',' t/h'],['Feed molino sólidos','vMill',' t/h'],['Feed ciclón sólidos','vCyclone',' t/h'],['Overflow sólidos','vOF',' t/h'],['Underflow sólidos','vUF',' t/h'],['Split U/F','vSplit',' %'],['P80 U/F','vP80UF',' µm'],['E específica','vSpecific',' kWh/t'],['Nivel sump','vSumpLevel',' %'],['Volumen sump','vSumpVolume',' m³'],['Ciclón w/w =','vCycloneSolids',' %'],['Densidad ciclón','vCycloneDensity',' t/m³'],['Caudal bomba','vPumpFlow',' m³/h'],['Agua overflow','vWaterOF',' m³/h'],['Agua underflow','vWaterUF',' m³/h'],['Residual sólidos sistema','vResid',' t/h'],['Residual ciclón sólidos','vResidC',' t/h'],['Residual agua sistema','vWaterResid',' t/h']].forEach(([n,id,u])=>table.insertAdjacentHTML('beforeend',`<tr><td>${n}</td><td><span id="${id}">—</span>${u}</td></tr>`));}
function applyStep(inputId,configKey,sourceId){const v=Math.max(0,num(inputId));disturb(configKey,v);if(sourceId)$(sourceId).value=v;}
enrich();$('calcBtn').onclick=calculate;$('resetBtn').onclick=calculate;$('playBtn').onclick=start;$('startupBtn').onclick=startup;$('pauseBtn').onclick=()=>{running=false;if(raf)cancelAnimationFrame(raf);raf=null;lastWall=null;update();};$('stopBtn').onclick=stop;$('disturbBtn').onclick=()=>{const v=config.freshSolidsTph*1.2;$('tph').value=v;disturb('freshSolidsTph',v)};const liveMillWater=()=>{if(!config||!state)return;config.millWaterM3h=Math.max(0,num('millWater'));config.millWaterControlMode=$('millWaterMode').value;config.millSolidsSetpointPct=Math.min(100,Math.max(0,num('millSolidsSP')));config.millWaterMinimumM3h=Math.max(0,num('millWaterMin'));config.millWaterMaximumM3h=Math.max(config.millWaterMinimumM3h+.01,num('millWaterMax'));config.millWaterGain=Math.max(.01,num('millWaterKp'));config.millWaterIntegralTimeMin=Math.max(.1,num('millWaterTi'));state.stableFor=0;state.status='TRANSITORIO';update();};['millWater','millSolidsSP','millWaterMin','millWaterMax','millWaterKp','millWaterTi'].forEach(id=>$(id).addEventListener('input',liveMillWater));$('millWaterMode').addEventListener('change',()=>{if(config&&state){const m=metric();if($('millWaterMode').value==='auto'){const error=m.solidsPctMillInventory-num('millSolidsSP');state.millWaterIntegral=m.W_mill_fresh+m.W_mill_recycle+m.W_mill_moisture-num('millWater')-Math.max(.01,num('millWaterKp'))*error}else{$('millWater').value=m.W_mill_fresh.toFixed(1);state.millWaterIntegral=0}}liveMillWater()});const livePump=()=>{if(!config||!state)return;config.pumpControlMode=$('pumpMode').value;config.sumpLevelSetpointPct=Math.min(100,Math.max(0,num('sumpLevelSP')));config.pumpSpeedPct=Math.min(100,Math.max(0,num('pumpSpeed')));config.pumpMinimumControlPct=Math.min(100,Math.max(0,num('pumpMinSpeed')));config.pumpMaxFlowM3h=Math.max(1,num('pumpMaxFlow'));config.pumpLevelGain=Math.max(.01,num('pumpKp'));config.pumpIntegralTimeMin=Math.max(.1,num('pumpTi'));state.stableFor=0;state.status='TRANSITORIO';update();};['sumpLevelSP','pumpSpeed','pumpMinSpeed','pumpMaxFlow','pumpKp','pumpTi'].forEach(id=>$(id).addEventListener('input',livePump));$('pumpMode').addEventListener('change',()=>{if(state)state.pumpIntegral=0;livePump()});$('stepFeedBtn').onclick=()=>applyStep('stepFeed','freshSolidsTph','tph');$('stepWiBtn').onclick=()=>applyStep('stepWi','wiKwhT','wi');$('stepMillWaterBtn').onclick=()=>applyStep('stepMillWater','millWaterM3h','millWater');$('stepSumpWaterBtn').onclick=()=>applyStep('stepSumpWater','sumpWaterM3h','sumpWater');$('stepPumpBtn').onclick=()=>applyStep('stepPumpSpeed','pumpSpeedPct','pumpSpeed');$('stepCyclonesBtn').onclick=()=>applyStep('stepCyclones','activeCyclones','activeCyclones');$('stepPressureBtn').onclick=()=>applyStep('stepPressure','feedPressureKpa','cyclonePressure');$('exportBtn').onclick=exportCSV;$('exportPSDExcel').onclick=exportPSDExcel;
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.pane').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.pane).classList.add('active');drawAll();});document.querySelectorAll('.left .section').forEach(h=>h.onclick=()=>{h.classList.toggle('collapsed');h.nextElementSibling?.classList.toggle('collapsed')});
calculate();
})();
