'use strict';
const E=require('../engine.js');
const EPS=1e-12,c=E.defaultConfig();
const responseVariables=['P80_OF','P80_mill','CL','M_mill','sumpLevelPct','densityCyclone','F_UF','F_OF','millWaterMassT','sumpWaterMassT'];
const tolerances={P80_OF:1,P80_mill:2,CL:1,M_mill:.5,sumpLevelPct:.2,densityCyclone:.01,F_UF:.5,F_OF:.2,millWaterMassT:.5,sumpWaterMassT:1};
const solved=E.solveSteadyState(c),ss=solved.metrics;
function responseStats(samples,key,y0,yss){const delta=yss-y0,den=Math.max(Math.abs(delta),EPS),direction=Math.sign(delta)||1,out={initial:y0,steadyState:yss,tolerance:tolerances[key]};for(const f of [.63,.90,.95,.99]){const hit=samples.find(x=>direction*(x[key]-y0)/den>=f);out[`T${Math.round(f*100)}`]=hit?hit.elapsedMin:null;}let suffix=true,entry=null;for(let i=samples.length-1;i>=0;i--){suffix=suffix&&Math.abs(samples[i][key]-yss)<=tolerances[key];if(suffix)entry=samples[i].elapsedMin;}out.permanentToleranceEntryMin=entry;return out;}
function startupAudit(){const s=E.startupState(c),initial=E.metrics(s,c),samples=[];for(let sec=0;sec<600*60;sec+=10){E.advance(s,c,10,1);samples.push({...E.metrics(s,c),elapsedMin:(sec+10)/60});}const variables=Object.fromEntries(responseVariables.map(k=>[k,responseStats(samples,k,initial[k],ss[k])]));return{steadyStateSolverTimeMin:solved.state.t,measurementHorizonMin:600,variables,orderedSlowToFast:Object.entries(variables).sort((a,b)=>(b[1].permanentToleranceEntryMin??Infinity)-(a[1].permanentToleranceEntryMin??Infinity)).map(([variable,x])=>({variable,permanentToleranceEntryMin:x.permanentToleranceEntryMin,T95:x.T95,T99:x.T99}))};}
function slope(points,key){const n=points.length,xbar=points.reduce((a,x)=>a+x.elapsedMin,0)/n,ybar=points.reduce((a,x)=>a+x[key],0)/n,num=points.reduce((a,x)=>a+(x.elapsedMin-xbar)*(x[key]-ybar),0),den=points.reduce((a,x)=>a+(x.elapsedMin-xbar)**2,0);return num/Math.max(den,EPS);}
function caseAudit(feed){const cc=E.defaultConfig({...c,freshSolidsTph:feed}),s=E.startupState(cc),samples=[];let pumpAtMax=0,pumpAtMin=0,waterSaturated=0;for(let minute=1;minute<=1800;minute++){E.advance(s,cc,60,2);const m=E.metrics(s,cc),d=E.flowModel(s,cc),pumpSaturation=d.effectiveSpeed>=100-EPS?'MAX':d.effectiveSpeed<=cc.pumpMinimumControlPct+EPS?'MIN':'NONE';if(pumpSaturation==='MAX')pumpAtMax++;if(pumpSaturation==='MIN')pumpAtMin++;if(d.millWaterSaturated)waterSaturated++;samples.push({elapsedMin:minute,...m,pumpIntegral:s.pumpIntegral,millWaterIntegral:s.millWaterIntegral,pumpSaturation,millWaterSaturated:d.millWaterSaturated,dPumpIntegral:d.dPumpIntegral,dMillWaterIntegral:d.dMillWaterIntegral});}
 const final=samples.at(-1),window=samples.slice(-120),keys=['Power_mill','M_mill','millWaterMassT','P80_mill','P80_OF','CL','F_mill','F_UF','F_OF','sumpLevelPct','pumpSpeedEffectivePct','Q_pump','d50c','densityCyclone','solidsPctCyclone','systemSolidsResidual','systemWaterResidual','solidsInventoryRate','waterInventoryRate'];
 const capacityExceeded=final.pumpSaturation==='MAX'&&final.sumpLevelPct>100&&final.solidsInventoryRate>0&&final.waterInventoryRate>0;
 return{feedTph:feed,horizonMin:1800,diagnosticState:capacityExceeded?'CAPACITY_EXCEEDED':'NO_STEADY_STATE',causeClasses:capacityExceeded?['A_MODELLED_PHYSICAL_LIMIT','B_ACTUATOR_SATURATION','F_NO_FINITE_STEADY_STATE']:['F_NO_FINITE_STEADY_STATE'],installedPowerKw:cc.installedPowerKw,availableShaftPowerAfterEfficiencyKw:cc.installedPowerKw*cc.mechanicalEfficiencyPct/100,final:Object.fromEntries(keys.map(k=>[k,final[k]])),finalControls:{pumpSaturation:final.pumpSaturation,millWaterSaturated:final.millWaterSaturated,pumpIntegral:final.pumpIntegral,millWaterIntegral:final.millWaterIntegral,dPumpIntegral:final.dPumpIntegral,dMillWaterIntegral:final.dMillWaterIntegral},saturationFraction:{pumpAtMax:pumpAtMax/1800,pumpAtMin:pumpAtMin/1800,millWater:waterSaturated/1800},last120MinSlopePerMin:Object.fromEntries(keys.map(k=>[k,slope(window,k)])),snapshots:[1,10,60,120,240,360,600,900,1200,1500,1800].map(t=>{const x=samples[t-1];return{elapsedMin:t,Power_mill:x.Power_mill,powerVsInstalledPct:100*x.Power_mill/cc.installedPowerKw,powerVsAvailablePct:100*x.Power_mill/(cc.installedPowerKw*cc.mechanicalEfficiencyPct/100),specificEnergy:x.specificEnergy,M_mill:x.M_mill,millWaterMassT:x.millWaterMassT,P80_mill:x.P80_mill,P80_OF:x.P80_OF,CL:x.CL,F_mill:x.F_mill,F_UF:x.F_UF,F_OF:x.F_OF,sumpLevelPct:x.sumpLevelPct,pumpSpeedEffectivePct:x.pumpSpeedEffectivePct,Q_pump:x.Q_pump,pumpSaturation:x.pumpSaturation,millWaterSaturated:x.millWaterSaturated,d50c:x.d50c,densityCyclone:x.densityCyclone,solidsPctCyclone:x.solidsPctCyclone,systemSolidsResidual:x.systemSolidsResidual,systemWaterResidual:x.systemWaterResidual,solidsInventoryRate:x.solidsInventoryRate,waterInventoryRate:x.waterInventoryRate};})};}
function powerSweep(){const rows=[];for(const feed of [50,75,100,125,150,175,200,225,250]){const cc=E.defaultConfig({...c,freshSolidsTph:feed}),x=E.solveSteadyState(cc),m=x.metrics;rows.push({feedTph:feed,converged:x.converged,timeMin:x.state.t,Power_mill:m.Power_mill,installedPowerKw:cc.installedPowerKw,availableAfterEfficiencyKw:cc.installedPowerKw*cc.mechanicalEfficiencyPct/100,powerVsInstalledPct:100*m.Power_mill/cc.installedPowerKw,powerVsAvailablePct:100*m.Power_mill/(cc.installedPowerKw*cc.mechanicalEfficiencyPct/100),specificEnergyKwhT:m.specificEnergy,P80_mill:m.P80_mill,P80_OF:m.P80_OF,CL:m.CL,M_mill:m.M_mill,solidsInventoryRate:m.solidsInventoryRate,waterInventoryRate:m.waterInventoryRate,status:m.status});}return rows;}
const report={generatedAt:new Date().toISOString(),config:{installedPowerKw:c.installedPowerKw,mechanicalEfficiencyPct:c.mechanicalEfficiencyPct,initialMillSolidsT:c.initialMillSolidsT,minimumPowerFraction:c.minimumPowerFraction,breakageCalibration:c.breakageCalibration,wiKwhT:c.wiKwhT,tauHoldMin:c.tauHoldMin},startup:startupAudit(),capacityCases:[caseAudit(150),caseAudit(200)],powerSweep:powerSweep()};
console.log(JSON.stringify(report,null,2));
