'use strict';
const E=require('../engine.js');
const base=E.defaultConfig(),EPS=1e-12;
const traceKeys=['F_UF','CL','F_cyclone','Q_pump','pumpSpeedEffectivePct','sumpLevelPct','sumpSolidsMassT','sumpWaterMassT','P80_mill','P80_OF','d50c','solidsPctCyclone','densityCyclone','split_UF','W_UF'];
function stats(samples,key,y0,yss){const delta=yss-y0,den=Math.max(Math.abs(delta),EPS),dir=Math.sign(delta)||1,out={};for(const f of [.63,.90,.95,.99]){const hit=samples.find(x=>dir*(x[key]-y0)/den>=f);out[`T${Math.round(f*100)}`]=hit?hit.t:null;}const extreme=dir>0?Math.max(...samples.map(x=>x[key])):Math.min(...samples.map(x=>x[key]));out.overshoot=Math.max(0,dir*(extreme-yss));return out;}
function permanentBand(samples,ss,fraction){let inside=true,entry=null;for(let i=samples.length-1;i>=0;i--){inside=inside&&Math.abs(samples[i].F_UF-ss.F_UF)/Math.max(Math.abs(ss.F_UF),EPS)<=fraction;if(inside)entry=samples[i].t;}return entry;}
function run(label,changes){const c=E.defaultConfig({...base,...changes}),solved=E.solveSteadyState(c),s=E.startupState(c),initial=E.metrics(s,c),samples=[];let prev=initial;for(let sec=0;sec<600*60;sec+=10){E.advance(s,c,10,1);const m=E.metrics(s,c);samples.push({...m,t:(sec+10)/60,dFUFdt:(m.F_UF-prev.F_UF)/(10/60)});prev=m;}const final=samples.at(-1),fuf=stats(samples,'F_UF',initial.F_UF,solved.metrics.F_UF),operational=m=>Math.abs(m.P80_OF-solved.metrics.P80_OF)/solved.metrics.P80_OF<=.02&&Math.abs(m.CL-solved.metrics.CL)/solved.metrics.CL<=.05&&Math.abs(m.F_UF-solved.metrics.F_UF)/solved.metrics.F_UF<=.05&&Math.abs(m.sumpLevelPct-solved.metrics.sumpLevelPct)<=2&&Math.abs(m.densityCyclone-solved.metrics.densityCyclone)/solved.metrics.densityCyclone<=.01;let operationalEntry=null,operationalRun=0;for(const m of samples){operationalRun=operational(m)?operationalRun+10:0;if(operationalRun>=600){operationalEntry=m.t-10;break;}}return{label,changes,steadyStateConverged:solved.converged,steadyState:{F_UF:solved.metrics.F_UF,CL:solved.metrics.CL,P80_OF:solved.metrics.P80_OF,sumpLevelPct:solved.metrics.sumpLevelPct,densityCyclone:solved.metrics.densityCyclone,sumpResidenceMin:60*solved.metrics.sumpVolumeM3/solved.metrics.Q_pump,millResidenceMin:c.tauHoldMin,ufSplit:solved.metrics.split_UF},T63_F_UF:fuf.T63,T90_F_UF:fuf.T90,T95_F_UF:fuf.T95,T99_F_UF:fuf.T99,tauEffectiveMin:(fuf.T63+fuf.T90/2.302585093+fuf.T95/2.995732274+fuf.T99/4.605170186)/4,T95_CL:stats(samples,'CL',initial.CL,solved.metrics.CL).T95,T95_P80_OF:stats(samples,'P80_OF',initial.P80_OF,solved.metrics.P80_OF).T95,T95_sumpLevel:stats(samples,'sumpLevelPct',initial.sumpLevelPct,solved.metrics.sumpLevelPct).T95,FUF_overshoot:fuf.overshoot,bands:Object.fromEntries([.05,.02,.01,.005,.001].map(x=>[`${100*x}%`,permanentBand(samples,solved.metrics,x)])),derivativeBandEntryMin:(()=>{let inside=true,entry=null;for(let i=samples.length-1;i>=0;i--){inside=inside&&Math.abs(samples[i].dFUFdt)<=c.tolerances.ufRate;if(inside)entry=samples[i].t;}return entry;})(),operationalStabilityEntryMin:operationalEntry,operationalCriteria:{windowMin:10,P80_OF_relative:.02,CL_relative:.05,F_UF_relative:.05,sumpLevelAbsolutePctPoints:2,densityCycloneRelative:.01},final:{F_UF:final.F_UF,CL:final.CL,P80_OF:final.P80_OF,sumpLevelPct:final.sumpLevelPct,status:final.status},snapshots:[1,5,10,30,60,120,240,360,480,600].map(t=>{const x=samples[Math.round(t*6)-1];return Object.fromEntries(['t',...traceKeys,'dFUFdt'].map(k=>[k,x[k]]));})};}
const scenarios=[
 ['tauHold_0.5x',{tauHoldMin:base.tauHoldMin*.5}],['baseline',{}],['tauHold_2x',{tauHoldMin:base.tauHoldMin*2}],
 ['tauCyclone_0.5x',{tauCycloneMin:base.tauCycloneMin*.5}],['tauCyclone_2x',{tauCycloneMin:base.tauCycloneMin*2}],
 ['sumpVolume_0.5x',{sumpVolumeM3:base.sumpVolumeM3*.5}],['sumpVolume_2x',{sumpVolumeM3:base.sumpVolumeM3*2}],
 ['pumpKp_0.5x',{pumpLevelGain:base.pumpLevelGain*.5}],['pumpKp_2x',{pumpLevelGain:base.pumpLevelGain*2}],
 ['pumpKi_0.5x',{pumpIntegralTimeMin:base.pumpIntegralTimeMin*2}],['pumpKi_2x',{pumpIntegralTimeMin:base.pumpIntegralTimeMin*.5}],
 ['breakage_0.8x',{breakageCalibration:base.breakageCalibration*.8}],['breakage_1.2x',{breakageCalibration:base.breakageCalibration*1.2}]
];
const selected=process.argv.includes('--baseline-only')?scenarios.filter(([label])=>label==='baseline'):scenarios,rows=selected.map(([label,changes])=>run(label,changes)),summaryOnly=process.argv.includes('--summary');
console.log(JSON.stringify({generatedAt:new Date().toISOString(),defaults:{tauHoldMin:base.tauHoldMin,tauCycloneMin:base.tauCycloneMin,sumpVolumeM3:base.sumpVolumeM3,pumpLevelGain:base.pumpLevelGain,pumpIntegralTimeMin:base.pumpIntegralTimeMin,breakageCalibration:base.breakageCalibration,ufDerivativeToleranceTphPerMin:base.tolerances.ufRate},rows:summaryOnly?rows.map(({snapshots,...x})=>x):rows},null,2));
